name: Waka Readme

on:
  schedule:
    # Runs at 12am IST (21:30 UTC)
    - cron: '30 21 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      issues: read
      pull-requests: read
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3

      - name: Print debug info
        run: echo "GH_TOKEN=${{ secrets.GITHUB_TOKEN }}"

      - name: Update Readme with WakaTime Metrics
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
